name: CI/CD Pipeline - Test and Report

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  NODE_VERSION: '18.x'
  CHROME_VERSION: 'latest'
  EDGE_VERSION: '136.0.3240.64'

jobs:
  test:
    name: Run Tests and Generate Report
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install System Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y wget unzip libgbm1

      - name: Install Chrome Browser
        uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: ${{ env.CHROME_VERSION }}

      - name: Install Project Dependencies
        run: npm ci --prefer-offline

      - name: Clean Report Directory
        run: npm run pretest

      - name: Run Test Suite
        run: npm run test
        env:
          CI: true
          HEADLESS: true

      - name: Generate Allure Report
        if: always()
        run: npm run allure:generate

      - name: Upload Allure Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-report-${{ github.run_id }}
          path: allure-report
          retention-days: 7

      - name: Upload Test Results
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: test-results-${{ github.run_id }}
          path: |
            test-results/
            logs/
          retention-days: 7